FROM container-registry.oracle.com/os/oraclelinux:9-slim

EXPOSE 8080

COPY target/rest-service-demo app
ENTRYPOINT ["/app"]

# Build and run:
# docker build -f ./Dockerfile.native -t localhost/rest-service-demo:upx .
# docker run --rm -p 8080:8080 localhost/rest-service-demo:upx